# Generated by Django 5.2.3 on 2025-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='icon_media/'),
        ),
    ]
