# Generated by Django 5.2.3 on 2025-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_myuser_date_of_birth_myuser_is_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_client",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="is_owner",
            field=models.BooleanField(default=False),
        ),
    ]
