# Generated by Django 5.2.3 on 2025-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_myuser_is_client_alter_myuser_is_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
